// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.depich1987.wsih.domain;

import com.depich1987.wsih.domain.WSMedecine;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect WSMedecine_Roo_Configurable {
    
    declare @type: WSMedecine: @Configurable;
    
}
