// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.depich1987.wsih.domain;

import com.depich1987.wsih.domain.WSInsuanceCompanyDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect WSInsuanceCompanyDataOnDemand_Roo_Configurable {
    
    declare @type: WSInsuanceCompanyDataOnDemand: @Configurable;
    
}
