// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.depich1987.wsih.domain;

import com.depich1987.wsih.domain.WSInsuanceCompanyDataOnDemand;
import com.depich1987.wsih.domain.WSInsuanceCompanyIntegrationTest;
import com.depich1987.wsih.domain.WSInsuranceCompany;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect WSInsuanceCompanyIntegrationTest_Roo_IntegrationTest {
    
    declare @type: WSInsuanceCompanyIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: WSInsuanceCompanyIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: WSInsuanceCompanyIntegrationTest: @Transactional;
    
    @Autowired
    WSInsuanceCompanyDataOnDemand WSInsuanceCompanyIntegrationTest.dod;
    
    @Test
    public void WSInsuanceCompanyIntegrationTest.testCountWSInsuranceCompanys() {
        Assert.assertNotNull("Data on demand for 'WSInsuranceCompany' failed to initialize correctly", dod.getRandomWSInsuranceCompany());
        long count = WSInsuranceCompany.countWSInsuranceCompanys();
        Assert.assertTrue("Counter for 'WSInsuranceCompany' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void WSInsuanceCompanyIntegrationTest.testFindWSInsuranceCompany() {
        WSInsuranceCompany obj = dod.getRandomWSInsuranceCompany();
        Assert.assertNotNull("Data on demand for 'WSInsuranceCompany' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'WSInsuranceCompany' failed to provide an identifier", id);
        obj = WSInsuranceCompany.findWSInsuranceCompany(id);
        Assert.assertNotNull("Find method for 'WSInsuranceCompany' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'WSInsuranceCompany' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void WSInsuanceCompanyIntegrationTest.testFindAllWSInsuranceCompanys() {
        Assert.assertNotNull("Data on demand for 'WSInsuranceCompany' failed to initialize correctly", dod.getRandomWSInsuranceCompany());
        long count = WSInsuranceCompany.countWSInsuranceCompanys();
        Assert.assertTrue("Too expensive to perform a find all test for 'WSInsuranceCompany', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<WSInsuranceCompany> result = WSInsuranceCompany.findAllWSInsuranceCompanys();
        Assert.assertNotNull("Find all method for 'WSInsuranceCompany' illegally returned null", result);
        Assert.assertTrue("Find all method for 'WSInsuranceCompany' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void WSInsuanceCompanyIntegrationTest.testFindWSInsuranceCompanyEntries() {
        Assert.assertNotNull("Data on demand for 'WSInsuranceCompany' failed to initialize correctly", dod.getRandomWSInsuranceCompany());
        long count = WSInsuranceCompany.countWSInsuranceCompanys();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<WSInsuranceCompany> result = WSInsuranceCompany.findWSInsuranceCompanyEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'WSInsuranceCompany' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'WSInsuranceCompany' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void WSInsuanceCompanyIntegrationTest.testFlush() {
        WSInsuranceCompany obj = dod.getRandomWSInsuranceCompany();
        Assert.assertNotNull("Data on demand for 'WSInsuranceCompany' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'WSInsuranceCompany' failed to provide an identifier", id);
        obj = WSInsuranceCompany.findWSInsuranceCompany(id);
        Assert.assertNotNull("Find method for 'WSInsuranceCompany' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyWSInsuranceCompany(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'WSInsuranceCompany' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void WSInsuanceCompanyIntegrationTest.testMergeUpdate() {
        WSInsuranceCompany obj = dod.getRandomWSInsuranceCompany();
        Assert.assertNotNull("Data on demand for 'WSInsuranceCompany' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'WSInsuranceCompany' failed to provide an identifier", id);
        obj = WSInsuranceCompany.findWSInsuranceCompany(id);
        boolean modified =  dod.modifyWSInsuranceCompany(obj);
        Integer currentVersion = obj.getVersion();
        WSInsuranceCompany merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'WSInsuranceCompany' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void WSInsuanceCompanyIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'WSInsuranceCompany' failed to initialize correctly", dod.getRandomWSInsuranceCompany());
        WSInsuranceCompany obj = dod.getNewTransientWSInsuranceCompany(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'WSInsuranceCompany' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'WSInsuranceCompany' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'WSInsuranceCompany' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void WSInsuanceCompanyIntegrationTest.testRemove() {
        WSInsuranceCompany obj = dod.getRandomWSInsuranceCompany();
        Assert.assertNotNull("Data on demand for 'WSInsuranceCompany' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'WSInsuranceCompany' failed to provide an identifier", id);
        obj = WSInsuranceCompany.findWSInsuranceCompany(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'WSInsuranceCompany' with identifier '" + id + "'", WSInsuranceCompany.findWSInsuranceCompany(id));
    }
    
}
