// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.depich1987.wsih.domain;

import com.depich1987.wsih.domain.WSInsuanceCompanyDataOnDemand;
import com.depich1987.wsih.domain.WSInsuranceCompany;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect WSInsuanceCompanyDataOnDemand_Roo_DataOnDemand {
    
    declare @type: WSInsuanceCompanyDataOnDemand: @Component;
    
    private Random WSInsuanceCompanyDataOnDemand.rnd = new SecureRandom();
    
    private List<WSInsuranceCompany> WSInsuanceCompanyDataOnDemand.data;
    
    public WSInsuranceCompany WSInsuanceCompanyDataOnDemand.getNewTransientWSInsuranceCompany(int index) {
        WSInsuranceCompany obj = new WSInsuranceCompany();
        setCompanyName(obj, index);
        setContact(obj, index);
        setEmail(obj, index);
        return obj;
    }
    
    public void WSInsuanceCompanyDataOnDemand.setCompanyName(WSInsuranceCompany obj, int index) {
        String companyName = "companyName_" + index;
        obj.setCompanyName(companyName);
    }
    
    public void WSInsuanceCompanyDataOnDemand.setContact(WSInsuranceCompany obj, int index) {
        String contact = "contact_" + index;
        obj.setContact(contact);
    }
    
    public void WSInsuanceCompanyDataOnDemand.setEmail(WSInsuranceCompany obj, int index) {
        String email = "foo" + index + "@bar.com";
        obj.setEmail(email);
    }
    
    public WSInsuranceCompany WSInsuanceCompanyDataOnDemand.getSpecificWSInsuranceCompany(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        WSInsuranceCompany obj = data.get(index);
        Long id = obj.getId();
        return WSInsuranceCompany.findWSInsuranceCompany(id);
    }
    
    public WSInsuranceCompany WSInsuanceCompanyDataOnDemand.getRandomWSInsuranceCompany() {
        init();
        WSInsuranceCompany obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return WSInsuranceCompany.findWSInsuranceCompany(id);
    }
    
    public boolean WSInsuanceCompanyDataOnDemand.modifyWSInsuranceCompany(WSInsuranceCompany obj) {
        return false;
    }
    
    public void WSInsuanceCompanyDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = WSInsuranceCompany.findWSInsuranceCompanyEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'WSInsuranceCompany' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<WSInsuranceCompany>();
        for (int i = 0; i < 10; i++) {
            WSInsuranceCompany obj = getNewTransientWSInsuranceCompany(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
