// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.depich1987.wsih.domain;

import com.depich1987.wsih.domain.WSMedecine;
import com.depich1987.wsih.domain.WSMedecineDataOnDemand;
import com.depich1987.wsih.domain.WSMedecineIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect WSMedecineIntegrationTest_Roo_IntegrationTest {
    
    declare @type: WSMedecineIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: WSMedecineIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: WSMedecineIntegrationTest: @Transactional;
    
    @Autowired
    WSMedecineDataOnDemand WSMedecineIntegrationTest.dod;
    
    @Test
    public void WSMedecineIntegrationTest.testCountWSMedecines() {
        Assert.assertNotNull("Data on demand for 'WSMedecine' failed to initialize correctly", dod.getRandomWSMedecine());
        long count = WSMedecine.countWSMedecines();
        Assert.assertTrue("Counter for 'WSMedecine' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void WSMedecineIntegrationTest.testFindWSMedecine() {
        WSMedecine obj = dod.getRandomWSMedecine();
        Assert.assertNotNull("Data on demand for 'WSMedecine' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'WSMedecine' failed to provide an identifier", id);
        obj = WSMedecine.findWSMedecine(id);
        Assert.assertNotNull("Find method for 'WSMedecine' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'WSMedecine' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void WSMedecineIntegrationTest.testFindAllWSMedecines() {
        Assert.assertNotNull("Data on demand for 'WSMedecine' failed to initialize correctly", dod.getRandomWSMedecine());
        long count = WSMedecine.countWSMedecines();
        Assert.assertTrue("Too expensive to perform a find all test for 'WSMedecine', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<WSMedecine> result = WSMedecine.findAllWSMedecines();
        Assert.assertNotNull("Find all method for 'WSMedecine' illegally returned null", result);
        Assert.assertTrue("Find all method for 'WSMedecine' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void WSMedecineIntegrationTest.testFindWSMedecineEntries() {
        Assert.assertNotNull("Data on demand for 'WSMedecine' failed to initialize correctly", dod.getRandomWSMedecine());
        long count = WSMedecine.countWSMedecines();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<WSMedecine> result = WSMedecine.findWSMedecineEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'WSMedecine' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'WSMedecine' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void WSMedecineIntegrationTest.testFlush() {
        WSMedecine obj = dod.getRandomWSMedecine();
        Assert.assertNotNull("Data on demand for 'WSMedecine' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'WSMedecine' failed to provide an identifier", id);
        obj = WSMedecine.findWSMedecine(id);
        Assert.assertNotNull("Find method for 'WSMedecine' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyWSMedecine(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'WSMedecine' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void WSMedecineIntegrationTest.testMergeUpdate() {
        WSMedecine obj = dod.getRandomWSMedecine();
        Assert.assertNotNull("Data on demand for 'WSMedecine' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'WSMedecine' failed to provide an identifier", id);
        obj = WSMedecine.findWSMedecine(id);
        boolean modified =  dod.modifyWSMedecine(obj);
        Integer currentVersion = obj.getVersion();
        WSMedecine merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'WSMedecine' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void WSMedecineIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'WSMedecine' failed to initialize correctly", dod.getRandomWSMedecine());
        WSMedecine obj = dod.getNewTransientWSMedecine(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'WSMedecine' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'WSMedecine' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'WSMedecine' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void WSMedecineIntegrationTest.testRemove() {
        WSMedecine obj = dod.getRandomWSMedecine();
        Assert.assertNotNull("Data on demand for 'WSMedecine' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'WSMedecine' failed to provide an identifier", id);
        obj = WSMedecine.findWSMedecine(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'WSMedecine' with identifier '" + id + "'", WSMedecine.findWSMedecine(id));
    }
    
}
