// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.depich1987.wsih.domain;

import com.depich1987.wsih.domain.WSMedecineType;
import com.depich1987.wsih.domain.WSMedecineTypeDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect WSMedecineTypeDataOnDemand_Roo_DataOnDemand {
    
    declare @type: WSMedecineTypeDataOnDemand: @Component;
    
    private Random WSMedecineTypeDataOnDemand.rnd = new SecureRandom();
    
    private List<WSMedecineType> WSMedecineTypeDataOnDemand.data;
    
    public WSMedecineType WSMedecineTypeDataOnDemand.getNewTransientWSMedecineType(int index) {
        WSMedecineType obj = new WSMedecineType();
        setDescription(obj, index);
        setName(obj, index);
        return obj;
    }
    
    public void WSMedecineTypeDataOnDemand.setDescription(WSMedecineType obj, int index) {
        String description = "description_" + index;
        obj.setDescription(description);
    }
    
    public void WSMedecineTypeDataOnDemand.setName(WSMedecineType obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    public WSMedecineType WSMedecineTypeDataOnDemand.getSpecificWSMedecineType(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        WSMedecineType obj = data.get(index);
        Long id = obj.getId();
        return WSMedecineType.findWSMedecineType(id);
    }
    
    public WSMedecineType WSMedecineTypeDataOnDemand.getRandomWSMedecineType() {
        init();
        WSMedecineType obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return WSMedecineType.findWSMedecineType(id);
    }
    
    public boolean WSMedecineTypeDataOnDemand.modifyWSMedecineType(WSMedecineType obj) {
        return false;
    }
    
    public void WSMedecineTypeDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = WSMedecineType.findWSMedecineTypeEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'WSMedecineType' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<WSMedecineType>();
        for (int i = 0; i < 10; i++) {
            WSMedecineType obj = getNewTransientWSMedecineType(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
