// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.depich1987.wsih.domain;

import com.depich1987.wsih.domain.WSMedecineDataOnDemand;
import com.depich1987.wsih.domain.WSStockPile;
import com.depich1987.wsih.domain.WSStockPileDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect WSStockPileDataOnDemand_Roo_DataOnDemand {
    
    declare @type: WSStockPileDataOnDemand: @Component;
    
    private Random WSStockPileDataOnDemand.rnd = new SecureRandom();
    
    private List<WSStockPile> WSStockPileDataOnDemand.data;
    
    @Autowired
    WSMedecineDataOnDemand WSStockPileDataOnDemand.wSMedecineDataOnDemand;
    
    public WSStockPile WSStockPileDataOnDemand.getNewTransientWSStockPile(int index) {
        WSStockPile obj = new WSStockPile();
        setCreatedBy(obj, index);
        setCreationDate(obj, index);
        setDescription(obj, index);
        setQuantity(obj, index);
        return obj;
    }
    
    public void WSStockPileDataOnDemand.setCreatedBy(WSStockPile obj, int index) {
        String createdBy = "createdBy_" + index;
        obj.setCreatedBy(createdBy);
    }
    
    public void WSStockPileDataOnDemand.setCreationDate(WSStockPile obj, int index) {
        Date creationDate = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setCreationDate(creationDate);
    }
    
    public void WSStockPileDataOnDemand.setDescription(WSStockPile obj, int index) {
        String description = "description_" + index;
        obj.setDescription(description);
    }
    
    public void WSStockPileDataOnDemand.setQuantity(WSStockPile obj, int index) {
        Long quantity = new Integer(index).longValue();
        obj.setQuantity(quantity);
    }
    
    public WSStockPile WSStockPileDataOnDemand.getSpecificWSStockPile(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        WSStockPile obj = data.get(index);
        Long id = obj.getId();
        return WSStockPile.findWSStockPile(id);
    }
    
    public WSStockPile WSStockPileDataOnDemand.getRandomWSStockPile() {
        init();
        WSStockPile obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return WSStockPile.findWSStockPile(id);
    }
    
    public boolean WSStockPileDataOnDemand.modifyWSStockPile(WSStockPile obj) {
        return false;
    }
    
    public void WSStockPileDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = WSStockPile.findWSStockPileEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'WSStockPile' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<WSStockPile>();
        for (int i = 0; i < 10; i++) {
            WSStockPile obj = getNewTransientWSStockPile(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
