// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.depich1987.wsih.domain;

import com.depich1987.wsih.domain.WSStockPile;
import com.depich1987.wsih.domain.WSStockPileDataOnDemand;
import com.depich1987.wsih.domain.WSStockPileIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect WSStockPileIntegrationTest_Roo_IntegrationTest {
    
    declare @type: WSStockPileIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: WSStockPileIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: WSStockPileIntegrationTest: @Transactional;
    
    @Autowired
    WSStockPileDataOnDemand WSStockPileIntegrationTest.dod;
    
    @Test
    public void WSStockPileIntegrationTest.testCountWSStockPiles() {
        Assert.assertNotNull("Data on demand for 'WSStockPile' failed to initialize correctly", dod.getRandomWSStockPile());
        long count = WSStockPile.countWSStockPiles();
        Assert.assertTrue("Counter for 'WSStockPile' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void WSStockPileIntegrationTest.testFindWSStockPile() {
        WSStockPile obj = dod.getRandomWSStockPile();
        Assert.assertNotNull("Data on demand for 'WSStockPile' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'WSStockPile' failed to provide an identifier", id);
        obj = WSStockPile.findWSStockPile(id);
        Assert.assertNotNull("Find method for 'WSStockPile' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'WSStockPile' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void WSStockPileIntegrationTest.testFindAllWSStockPiles() {
        Assert.assertNotNull("Data on demand for 'WSStockPile' failed to initialize correctly", dod.getRandomWSStockPile());
        long count = WSStockPile.countWSStockPiles();
        Assert.assertTrue("Too expensive to perform a find all test for 'WSStockPile', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<WSStockPile> result = WSStockPile.findAllWSStockPiles();
        Assert.assertNotNull("Find all method for 'WSStockPile' illegally returned null", result);
        Assert.assertTrue("Find all method for 'WSStockPile' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void WSStockPileIntegrationTest.testFindWSStockPileEntries() {
        Assert.assertNotNull("Data on demand for 'WSStockPile' failed to initialize correctly", dod.getRandomWSStockPile());
        long count = WSStockPile.countWSStockPiles();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<WSStockPile> result = WSStockPile.findWSStockPileEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'WSStockPile' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'WSStockPile' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void WSStockPileIntegrationTest.testFlush() {
        WSStockPile obj = dod.getRandomWSStockPile();
        Assert.assertNotNull("Data on demand for 'WSStockPile' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'WSStockPile' failed to provide an identifier", id);
        obj = WSStockPile.findWSStockPile(id);
        Assert.assertNotNull("Find method for 'WSStockPile' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyWSStockPile(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'WSStockPile' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void WSStockPileIntegrationTest.testMergeUpdate() {
        WSStockPile obj = dod.getRandomWSStockPile();
        Assert.assertNotNull("Data on demand for 'WSStockPile' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'WSStockPile' failed to provide an identifier", id);
        obj = WSStockPile.findWSStockPile(id);
        boolean modified =  dod.modifyWSStockPile(obj);
        Integer currentVersion = obj.getVersion();
        WSStockPile merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'WSStockPile' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void WSStockPileIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'WSStockPile' failed to initialize correctly", dod.getRandomWSStockPile());
        WSStockPile obj = dod.getNewTransientWSStockPile(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'WSStockPile' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'WSStockPile' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'WSStockPile' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void WSStockPileIntegrationTest.testRemove() {
        WSStockPile obj = dod.getRandomWSStockPile();
        Assert.assertNotNull("Data on demand for 'WSStockPile' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'WSStockPile' failed to provide an identifier", id);
        obj = WSStockPile.findWSStockPile(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'WSStockPile' with identifier '" + id + "'", WSStockPile.findWSStockPile(id));
    }
    
}
